export const GET_GLOBAL_DASHBOARD = 'GET_GLOBAL_TOTAL'
export const GET_GLOBAL_TIMESTAMP = 'GET_GLOBAL_TIMESTAMP'
export const GET_GLOBAL_COUNTRIES = 'GET_GLOBAL_COUNTRIES'

export const GET_INDIA_DASHBOARD = 'GET_INDIA_DASHBOARD'
export const GET_INDIA_TIMESTAMP = 'GET_INDIA_TIMESTAMP'
export const GET_INDIA_STATES = 'GET_INDIA_STATES'
