export const stateNames = {
	AN: 'Andaman & Nicobar Islands',
	AP: 'Andhra Pradesh',
	AR: 'Arunachal Pradesh',
	AS: 'Assam',
	BR: 'Bihar',
	CH: 'Chandigarh',
	CT: 'Chhattisgarh',
	DL: 'Delhi',
	DN: 'Dadra & Nagar Haveli & Daman & Diu',
	GA: 'Goa',
	GJ: 'Gujarat',
	HP: 'Himachal Pradesh',
	HR: 'Haryana',
	JH: 'Jharkhand',
	JK: 'Jammu & Kashmir',
	KA: 'Karnataka',
	KL: 'Kerala',
	LA: 'Ladakh',
	LD: 'Lakshadweep',
	MH: 'Maharashtra',
	ML: 'Meghalaya',
	MN: 'Manipur',
	MP: 'Madhya Pradesh',
	MZ: 'Mizoram',
	NL: 'Nagaland',
	OR: 'Odisha',
	PB: 'Punjab',
	PY: 'Puducherry',
	RJ: 'Rajasthan',
	SK: 'Sikkim',
	TG: 'Telangana',
	TN: 'Tamil Nadu',
	TR: 'Tripura',
	UN: 'State unassigned',
	UP: 'Uttar Pradesh',
	UT: 'Uttarakhand',
	WB: 'West Bengal'
}
